twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        assets_version: 39
        countries:
            Europe: ''
            Belgium: 'be'
            Canada: 'ca'
            France: 'fr'
            Germany: 'de'
            Italy: 'it'
            Japan: 'jp'
            Mexico: 'mx'
            Norway: 'sj'
            Netherlands: 'nl'
            Russia: 'ru'
            Slovenia: 'si'
            Sweden: 'se'
            Switzerland: 'ch'
            Turkey: 'tr'
            UK: 'gb'
            US: 'us'
