twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        countries:
            Europe: ''
            Belgium: 'be'
            Germany: 'de'
            Russia: 'ru'
            UK: 'gb'
            US: 'us'
            Norway: 'sj'
            Sweden: 'se'
            Switzerland: 'ch'
            Italy: 'it'

