admin_home:
    path: /admin/home
    controller: App\Controller\AdminController::home
    methods: [GET]

admin_song_validated:
    path: /admin/song/validated
    controller: App\Controller\AdminController::songValidated
    methods: [POST]

admin_release_style:
    path: /admin/release/{idRelease}/style/{idStyle}
    controller: App\Controller\AdminController::releaseStyle
    methods: [GET]

admin_song_patch:
    path: /admin/song/{id}
    controller: App\Controller\SongController::patch
    methods: [PATCH]
    requirements:
      id: '\d+'

admin_upload_cover:
    path: /admin/upload_cover
    controller: App\Controller\AdminController::uploadCover
    methods: [POST]

admin_upload_mp3:
    path: /admin/upload_mp3
    controller: App\Controller\AdminController::uploadMp3
    methods: [POST]
