autocomplete_artist_group:
    path: /autocomplete/artist_group/{prefixArtist}
    methods: GET
    controller: App\Controller\AutocompleteController::artistGroup

autocomplete_artist_songs:
    path: /autocomplete/artist/{artistId}/songs/{prefixSong}
    methods: GET
    controller: App\Controller\AutocompleteController::songsByArtist

autocomplete_styles:
    path: /autocomplete/styles
    methods: GET
    controller: App\Controller\AutocompleteController::styles