misc_contact:
    path: /contact
    controller: App\Controller\MiscController::contact
    methods: [GET, POST]

misc_terms:
    path: /terms
    controller: App\Controller\MiscController::terms
    methods: [GET]

sitemap:
    path: sitemap.xml
    controller: App\Controller\MiscController::sitemap
    methods: [GET]