song_add:
    path: /song/add
    controller: App\Controller\SongController::add
    methods: [POST]

song_patch:
    path: /admin/song/{id}
    controller: App\Controller\SongController::patch
    methods: [PATCH]
    requirements:
          id: '\d+'