style_list:
    path: /styles
    controller: App\Controller\StyleController::list
    methods: [GET]
style_home:
    path: /style/{idStyle}-{slug}
    controller: App\Controller\StyleController::home
    methods: [GET]
    requirements:
        id: '\d+'
