vote_song:
    path: /vote/song/{id}
    controller: App\Controller\VoteController::voteSong
    methods: [GET, POST]
    requirements:
        songId: '\d+'

vote_artist:
    path: /vote/artist/{id}
    controller: App\Controller\VoteController::voteArtist
    methods: [POST]
    requirements:
        songId: '\d+'