imports:
    resource: 'routes/auth_users.yaml'

index:
  path: /
  controller: App\Controller\HomeController::index

autocomplete:
    resource: 'routes/autocomplete.yaml'

song:
    resource: 'routes/song.yaml'

vote:
    resource: 'routes/vote.yaml'

admin:
    resource: 'routes/admin.yaml'

user:
    resource: 'routes/user.yaml'

misc:
    resource: 'routes/misc.yaml'