imports:
    resource: 'routes/auth_users.yaml'

index:
  path: /
  controller: App\Controller\DefaultController::index

autocomplete:
    resource: 'routes/autocomplete.yaml'

song:
    resource: 'routes/song.yaml'

admin:
    resource: 'routes/admin.yaml'
